version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - alumni-network

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - alumni-network

  # backend:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - .:/app
  #     - backend_media:/app/app/media
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env
  #   networks:
  #     - alumni-network
  #   environment:
  #     - POSTGRES_SERVER=db  # Important: use the service name as host

networks:
  alumni-network:
    driver: bridge

volumes:
  postgres_data:
  # backend_media: